package compiler.model;

public enum TokenType {
    CHAR,
    NON_CONSUMABLE,
    INTEGER_NUMBER,
    REAL_NUMBER,
    IDENTIFIER,
    RESERVED_WORD,
    ARITHMETIC_OPERATOR_SUM,
    ARITHMETIC_OPERATOR_SUBTRACTION,
    ARITHMETIC_OPERATOR_MULTIPLICATION,
    ARITHMETIC_OPERATOR_DIVISION,
    ARITHMETIC_OPERATOR_ATTRIBUTION,
    RELATIONAL_OPERATOR_EQUAL,
    RELATIONAL_OPERATOR_DIFFERENT,
    RELATIONAL_OPERATOR_LESS_THAN,
    RELATIONAL_OPERATOR_GREATER_THAN,
    RELATIONAL_OPERATOR_LESS_THAN_OR_EQUAL_TO,
    RELATIONAL_OPERATOR_GREATER_THAN_OR_EQUAL_TO,
    SPECIAL_CHARACTER_COMMA,
    SPECIAL_CHARACTER_SEMICOLON,
    SPECIAL_CHARACTER_OPEN_PARENTHESIS,
    SPECIAL_CHARACTER_CLOSE_PARENTHESIS,
    SPECIAL_CHARACTER_OPEN_CURLY_BRACKET,
    SPECIAL_CHARACTER_CLOSE_CURLY_BRACKET;
}
